services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8000}:3000"
    command: ["yarn", "start:server"]
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: vendure
      DB_USERNAME: postgres
      DB_PASSWORD: password

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["yarn", "start:worker"]
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: vendure
      DB_USERNAME: postgres
      DB_PASSWORD: password

  database:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vendure